package com.akash.webApp.Service.OnStartup;

import java.util.List;

import org.springframework.beans.factory.InitializingBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationListener;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import com.akash.webApp.Model.District;
import com.akash.webApp.Model.Role;
import com.akash.webApp.Model.RoleEnum;
import com.akash.webApp.Model.StateOrUt;
import com.akash.webApp.Model.UsersModel;
import com.akash.webApp.Repository.DistrictRepo;
import com.akash.webApp.Repository.RoleRepo;
import com.akash.webApp.Repository.StateOrUtRepo;
@Component
public class StartupRun implements InitializingBean 
{

    @Autowired
    private StateOrUtRepo stateOrUtRepo;
    @Autowired
    private DistrictRepo districtRepo;

    @Autowired 
    private RoleRepo roleRepo;



    List<StateOrUt> stateOrUts = List.of(
            new StateOrUt("Andaman and Nicobar Islands", 1),
            new StateOrUt("Andhra Pradesh", 2),
            new StateOrUt("Arunachal Pradesh", 3),
            new StateOrUt("Assam", 4),
            new StateOrUt("Bihar", 5),
            new StateOrUt("Chandigarh", 6),
            new StateOrUt("Chhattisgarh", 7),
            new StateOrUt("Dadra and Nagar Haveli and Daman and Diu", 8),
            new StateOrUt("Delhi", 9),
            new StateOrUt("Goa", 10),
            new StateOrUt("Gujarat", 11),
            new StateOrUt("Haryana", 12),
            new StateOrUt("Himachal Pradesh", 13),
            new StateOrUt("Jammu & Kashmir", 14),
            new StateOrUt("Jharkhand", 15),
            new StateOrUt("Karnataka", 16),
            new StateOrUt("Kerala", 17),
            new StateOrUt("Ladakh", 18),
            new StateOrUt("Lakshadweep", 19),
            new StateOrUt("Madhya Pradesh", 20),
            new StateOrUt("Maharashtra", 21),
            new StateOrUt("Manipur", 22),
            new StateOrUt("Meghalaya", 23),
            new StateOrUt("Mizoram", 24),
            new StateOrUt("Nagaland", 25),
            new StateOrUt("Odisha", 26),
            new StateOrUt("Puducherry", 27),
            new StateOrUt("Punjab", 28),
            new StateOrUt("Rajasthan", 29),
            new StateOrUt("Sikkim", 30),
            new StateOrUt("Tamil Nadu", 31),
            new StateOrUt("Telangana", 32),
            new StateOrUt("Tripura", 33),
            new StateOrUt("Uttar Pradesh", 34),
            new StateOrUt("Uttarakhand", 35),
            new StateOrUt("West Bengal", 36));

    List<District> districts = List.of(
            new District("Nicobars", 603,stateOrUts.get( 1-1)),
            new District("North And Middle Andaman", 632,stateOrUts.get( 1-1)),
            new District("South Andamans", 602,stateOrUts.get( 1-1)),

            new District("Alluri Sitharama Raju", 745,stateOrUts.get( 2-1)),
            new District("Anakapalli", 744,stateOrUts.get( 2-1)),
            new District("Ananthapuramu", 502,stateOrUts.get( 2-1)),
            new District("Annamayya", 753,stateOrUts.get( 2-1)),
            new District("Bapatla", 750,stateOrUts.get( 2-1)),
            new District("Chittoor", 503,stateOrUts.get( 2-1)),
            new District("Dr. B.R. Ambedkar Konaseema", 747,stateOrUts.get( 2-1)),
            new District("East Godavari", 505,stateOrUts.get( 2-1)),
            new District("Eluru", 748,stateOrUts.get( 2-1)),
            new District("Guntur", 506,stateOrUts.get( 2-1)),
            new District("Kakinada", 746,stateOrUts.get( 2-1)),
            new District("Krishna", 510,stateOrUts.get( 2-1)),
            new District("Kurnool", 511,stateOrUts.get( 2-1)),
            new District("Markapuram", 790,stateOrUts.get( 2-1)),
            new District("Nandyal", 755,stateOrUts.get( 2-1)),
            new District("Ntr", 749,stateOrUts.get( 2-1)),
            new District("Palnadu", 751,stateOrUts.get( 2-1)),
            new District("Parvathipuram Manyam", 743,stateOrUts.get( 2-1)),
            new District("Polavaram", 791,stateOrUts.get( 2-1)),
            new District("Prakasam", 517,stateOrUts.get( 2-1)),
            new District("Srikakulam", 519,stateOrUts.get( 2-1)),
            new District("Sri Potti Sriramulu Nellore", 515,stateOrUts.get( 2-1)),
            new District("Sri Sathya Sai", 754,stateOrUts.get( 2-1)),
            new District("Tirupati", 752,stateOrUts.get( 2-1)),
            new District("Visakhapatnam", 520,stateOrUts.get( 2-1)),
            new District("Vizianagaram", 521,stateOrUts.get( 2-1)),
            new District("West Godavari", 523,stateOrUts.get( 2-1)),
            new District("Y.S.R. Kadapa", 504,stateOrUts.get( 2-1)),

            new District("Anjaw", 628,stateOrUts.get( 3-1)),
            new District("Bichom", 787,stateOrUts.get( 3-1)),
            new District("Changlang", 229,stateOrUts.get( 3-1)),
            new District("Dibang Valley", 230,stateOrUts.get( 3-1)),
            new District("East Kameng", 231,stateOrUts.get( 3-1)),
            new District("East Siang", 232,stateOrUts.get( 3-1)),
            new District("Kamle", 718,stateOrUts.get( 3-1)),
            new District("Keyi Panyor", 786,stateOrUts.get( 3-1)),
            new District("Kra Daadi", 677,stateOrUts.get( 3-1)),
            new District("Kurung Kumey", 233,stateOrUts.get( 3-1)),
            new District("Leparada", 724,stateOrUts.get( 3-1)),
            new District("Lohit", 234,stateOrUts.get( 3-1)),
            new District("Longding", 666,stateOrUts.get( 3-1)),
            new District("Lower Dibang Valley", 235,stateOrUts.get( 3-1)),
            new District("Lower Siang", 719,stateOrUts.get( 3-1)),
            new District("Lower Subansiri", 236,stateOrUts.get( 3-1)),
            new District("Namsai", 678,stateOrUts.get( 3-1)),
            new District("Pakke Kessang", 723,stateOrUts.get( 3-1)),
            new District("Papum Pare", 237,stateOrUts.get( 3-1)),
            new District("Shi Yomi", 725,stateOrUts.get( 3-1)),
            new District("Siang", 679,stateOrUts.get( 3-1)),
            new District("Tawang", 238,stateOrUts.get( 3-1)),
            new District("Tirap", 239,stateOrUts.get( 3-1)),
            new District("Upper Siang", 240,stateOrUts.get( 3-1)),
            new District("Upper Subansiri", 241,stateOrUts.get( 3-1)),
            new District("West Kameng", 242,stateOrUts.get( 3-1)),
            new District("West Siang", 243,stateOrUts.get( 3-1)),

            new District("Bajali", 739,stateOrUts.get( 4-1)),
            new District("Baksa", 616,stateOrUts.get( 4-1)),
            new District("Barpeta", 280,stateOrUts.get( 4-1)),
            new District("Biswanath", 705,stateOrUts.get( 4-1)),
            new District("Bongaigaon", 281,stateOrUts.get( 4-1)),
            new District("Cachar", 282,stateOrUts.get( 4-1)),
            new District("Charaideo", 708,stateOrUts.get( 4-1)),
            new District("Chirang", 612,stateOrUts.get( 4-1)),
            new District("Darrang", 283,stateOrUts.get( 4-1)),
            new District("Dhemaji", 284,stateOrUts.get( 4-1)),
            new District("Dhubri", 285,stateOrUts.get( 4-1)),
            new District("Dibrugarh", 286,stateOrUts.get( 4-1)),
            new District("Dima Hasao", 299,stateOrUts.get( 4-1)),
            new District("Goalpara", 287,stateOrUts.get( 4-1)),
            new District("Golaghat", 288,stateOrUts.get( 4-1)),
            new District("Hailakandi", 289,stateOrUts.get( 4-1)),
            new District("Hojai", 709,stateOrUts.get( 4-1)),
            new District("Jorhat", 290,stateOrUts.get( 4-1)),
            new District("Kamrup", 291,stateOrUts.get( 4-1)),
            new District("Kamrup Metro", 618,stateOrUts.get( 4-1)),
            new District("Karbi Anglong", 292,stateOrUts.get( 4-1)),
            new District("Kokrajhar", 294,stateOrUts.get( 4-1)),
            new District("Lakhimpur", 295,stateOrUts.get( 4-1)),
            new District("Majuli", 706,stateOrUts.get( 4-1)),
            new District("Marigaon", 296,stateOrUts.get( 4-1)),
            new District("Nagaon", 297,stateOrUts.get( 4-1)),
            new District("Nalbari", 298,stateOrUts.get( 4-1)),
            new District("Sivasagar", 300,stateOrUts.get( 4-1)),
            new District("Sonitpur", 301,stateOrUts.get( 4-1)),
            new District("South Salmara Mancachar", 707,stateOrUts.get( 4-1)),
            new District("Sribhumi", 293,stateOrUts.get( 4-1)),
            new District("Tamulpur", 756,stateOrUts.get( 4-1)),
            new District("Tinsukia", 302,stateOrUts.get( 4-1)),
            new District("Udalguri", 617,stateOrUts.get( 4-1)),
            new District("West Karbi Anglong", 710,stateOrUts.get( 4-1)),

            new District("Araria", 188,stateOrUts.get( 5-1)),
            new District("Arwal", 611,stateOrUts.get( 5-1)),
            new District("Aurangabad", 189,stateOrUts.get( 5-1)),
            new District("Banka", 190,stateOrUts.get( 5-1)),
            new District("Begusarai", 191,stateOrUts.get( 5-1)),
            new District("Bhagalpur", 192,stateOrUts.get( 5-1)),

            new District("Bhojpur", 193,stateOrUts.get( 5-1)),
            new District("Buxar", 194,stateOrUts.get( 5-1)),
            new District("Darbhanga", 195,stateOrUts.get( 5-1)),
            new District("Gaya", 196,stateOrUts.get( 5-1)),
            new District("Gopalganj", 197,stateOrUts.get( 5-1)),
            new District("Jamui", 198,stateOrUts.get( 5-1)),
            new District("Jehanabad", 199,stateOrUts.get( 5-1)),
            new District("Kaimur (BhabstateOrUts.get(ua-1))", 200,stateOrUts.get( 5-1)),
            new District("Katihar", 201,stateOrUts.get( 5-1)),
            new District("Khagaria", 202,stateOrUts.get( 5-1)),
            new District("Kishanganj", 203,stateOrUts.get( 5-1)),
            new District("Lakhisarai", 204,stateOrUts.get( 5-1)),
            new District("Madhepura", 205,stateOrUts.get( 5-1)),
            new District("Madhubani", 206,stateOrUts.get( 5-1)),
            new District("Munger", 207,stateOrUts.get( 5-1)),
            new District("Muzaffarpur", 208,stateOrUts.get( 5-1)),
            new District("Nalanda", 209,stateOrUts.get( 5-1)),
            new District("Nawada", 210,stateOrUts.get( 5-1)),
            new District("Pashchim Champaran", 211,stateOrUts.get( 5-1)),
            new District("Patna", 212,stateOrUts.get( 5-1)),
            new District("Purbi Champaran", 213,stateOrUts.get( 5-1)),
            new District("Purnia", 214,stateOrUts.get( 5-1)),
            new District("Rohtas", 215,stateOrUts.get( 5-1)),
            new District("Saharsa", 216,stateOrUts.get( 5-1)),
            new District("Samastipur", 217,stateOrUts.get( 5-1)),
            new District("Saran", 218,stateOrUts.get( 5-1)),
            new District("Sheikhpura", 219,stateOrUts.get( 5-1)),
            new District("Sheohar", 220,stateOrUts.get( 5-1)),
            new District("Sitamarhi", 221,stateOrUts.get( 5-1)),
            new District("Siwan", 222,stateOrUts.get( 5-1)),
            new District("Supaul", 223,stateOrUts.get( 5-1)),
            new District("Vaishali", 224,stateOrUts.get( 5-1)),

            new District("Chandigarh", 44,stateOrUts.get( 6-1)),

            new District("Balod", 646,stateOrUts.get( 7-1)),
            new District("Balodabazar-Bhatapara", 644,stateOrUts.get( 7-1)),
            new District("Balrampur-Ramanujganj", 649,stateOrUts.get( 7-1)),
            new District("Bastar", 374,stateOrUts.get( 7-1)),
            new District("Bemetara", 650,stateOrUts.get( 7-1)),
            new District("Bijapur", 636,stateOrUts.get( 7-1)),
            new District("Bilaspur", 375,stateOrUts.get( 7-1)),
            new District("Dakshin Bastar Dantewada", 376,stateOrUts.get( 7-1)),
            new District("Dhamtari", 377,stateOrUts.get( 7-1)),
            new District("Durg", 378,stateOrUts.get( 7-1)),
            new District("Gariyaband", 645,stateOrUts.get( 7-1)),
            new District("Gaurela-Pendra-Marwahi", 734,stateOrUts.get( 7-1)),
            new District("Janjgir-Champa", 379,stateOrUts.get( 7-1)),
            new District("Jashpur", 380,stateOrUts.get( 7-1)),
            new District("Kabeerdham", 382,stateOrUts.get( 7-1)),
            new District("Khairagarh-Chhuikhadan-Gandai", 759,stateOrUts.get( 7-1)),
            new District("Kondagaon", 643,stateOrUts.get( 7-1)),
            new District("Korba", 383,stateOrUts.get( 7-1)),
            new District("Korea", 384,stateOrUts.get( 7-1)),
            new District("Mahasamund", 385,stateOrUts.get( 7-1)),
            new District("Manendragarh-Chirmiri-Bharatpur(M CstateOrUts.get( B-1))", 760,stateOrUts.get( 7-1)),
            new District("Mohla-Manpur-Ambagarh Chouki", 761,stateOrUts.get( 7-1)),
            new District("Mungeli", 647,stateOrUts.get( 7-1)),
            new District("Narayanpur", 637,stateOrUts.get( 7-1)),
            new District("Raigarh", 386,stateOrUts.get( 7-1)),
            new District("Raipur", 387,stateOrUts.get( 7-1)),
            new District("Rajnandgaon", 388,stateOrUts.get( 7-1)),
            new District("Sakti", 762,stateOrUts.get( 7-1)),
            new District("Sarangarh-Bilaigarh", 763,stateOrUts.get( 7-1)),
            new District("Sukma", 642,stateOrUts.get( 7-1)),
            new District("Surajpur", 648,stateOrUts.get( 7-1)),
            new District("Surguja", 38,stateOrUts.get( 7-1)),
            new District("Uttar Bastar Kanker", 381,stateOrUts.get( 7-1)),

            new District("Dadra And Nagar Haveli", 465,stateOrUts.get( 8-1)),
            new District("Daman", 463,stateOrUts.get( 8-1)),
            new District("Diu", 464,stateOrUts.get( 8-1))

            ,

            new District("Central", 77,stateOrUts.get( 9-1)),
            new District("East", 78,stateOrUts.get( 9-1)),
            new District("New Delhi", 79,stateOrUts.get( 9-1)),
            new District("North", 80,stateOrUts.get( 9-1)),
            new District("North East", 81,stateOrUts.get( 9-1)),
            new District("North West", 82,stateOrUts.get( 9-1)),
            new District("Shahdara", 671,stateOrUts.get( 9-1)),
            new District("South", 83,stateOrUts.get( 9-1)),
            new District("South East", 670,stateOrUts.get( 9-1)),
            new District("South West", 84,stateOrUts.get( 9-1)),
            new District("West", 85,stateOrUts.get( 9-1)),

            new District("Kushavati", 793, stateOrUts.get(10-1)),
            new District("North Goa", 551, stateOrUts.get(10-1)),
            new District("South Goa", 552, stateOrUts.get(10-1)),

            new District("Ahmedabad", 438, stateOrUts.get(11-1)),
            new District("Amreli", 439, stateOrUts.get(11-1)),
            new District("Anand", 440, stateOrUts.get(11-1)),
            new District("Arvalli", 672, stateOrUts.get(11-1)),
            new District("Banas Kantha", 441, stateOrUts.get(11-1)),
            new District("Bharuch", 442, stateOrUts.get(11-1)),
            new District("Bhavnagar", 443, stateOrUts.get(11-1)),
            new District("Botad", 676, stateOrUts.get(11-1)),
            new District("Chhotaudepur", 668, stateOrUts.get(11-1)),
            new District("Dahod", 445, stateOrUts.get(11-1)),
            new District("Dangs", 444, stateOrUts.get(11-1)),
            new District("Devbhumi Dwarka", 674, stateOrUts.get(11-1)),
            new District("Gandhinagar", 446, stateOrUts.get(11-1)),
            new District("Gir Somnath", 675, stateOrUts.get(11-1)),
            new District("Jamnagar", 447, stateOrUts.get(11-1)),
            new District("Junagadh", 448, stateOrUts.get(11-1)),
            new District("Kachchh", 449, stateOrUts.get(11-1)),
            new District("Kheda", 450, stateOrUts.get(11-1)),
            new District("Mahesana", 451, stateOrUts.get(11-1)),
            new District("Mahisagar", 669, stateOrUts.get(11-1)),
            new District("Morbi", 673, stateOrUts.get(11-1)),
            new District("Narmada", 452, stateOrUts.get(11-1)),
            new District("Navsari", 453, stateOrUts.get(11-1)),
            new District("Panch Mahals", 454, stateOrUts.get(11-1)),
            new District("Patan", 455, stateOrUts.get(11-1)),
            new District("Porbandar", 456, stateOrUts.get(11-1)),
            new District("Rajkot", 457, stateOrUts.get(11-1)),
            new District("Sabar Kantha", 458, stateOrUts.get(11-1)),
            new District("Surat", 459, stateOrUts.get(11-1)),
            new District("Surendranagar", 460, stateOrUts.get(11-1)),
            new District("Tapi", 641, stateOrUts.get(11-1)),
            new District("Vadodara", 461, stateOrUts.get(11-1)),
            new District("Valsad", 462, stateOrUts.get(11-1)),
            new District("Vav-Tharad", 789, stateOrUts.get(11-1)),

            new District("Ambala", 58, stateOrUts.get(12-1)),
            new District("Bhiwani", 59, stateOrUts.get(12-1)),
            new District("Charkhi Dadri", 701, stateOrUts.get(12-1)),
            new District("Faridabad", 60, stateOrUts.get(12-1)),
            new District("Fatehabad", 61, stateOrUts.get(12-1)),
            new District("Gurugram", 62, stateOrUts.get(12-1)),
            new District("Hansi", 792, stateOrUts.get(12-1)),
            new District("Hisar", 63, stateOrUts.get(12-1)),
            new District("Jhajjar", 64, stateOrUts.get(12-1)),
            new District("Jind", 65, stateOrUts.get(12-1)),
            new District("Kaithal", 66, stateOrUts.get(12-1)),
            new District("Karnal", 67, stateOrUts.get(12-1)),
            new District("Kurukshetra", 68, stateOrUts.get(12-1)),
            new District("Mahendragarh", 69, stateOrUts.get(12-1)),
            new District("Nuh", 604, stateOrUts.get(12-1)),
            new District("Palwal", 619, stateOrUts.get(12-1)),
            new District("Panchkula", 70, stateOrUts.get(12-1)),
            new District("Panipat", 71, stateOrUts.get(12-1)),
            new District("Rewari", 72, stateOrUts.get(12-1)),
            new District("Rohtak", 73, stateOrUts.get(12-1)),
            new District("Sirsa", 74, stateOrUts.get(12-1)),
            new District("Sonipat", 75, stateOrUts.get(12-1)),
            new District("Yamunanagar", 76, stateOrUts.get(12-1)),

            new District("Bilaspur", 15, stateOrUts.get(13-1)),
            new District("Chamba", 16, stateOrUts.get(13-1)),
            new District("Hamirpur", 17, stateOrUts.get(13-1)),
            new District("Kangra", 18, stateOrUts.get(13-1)),
            new District("Kinnaur", 19, stateOrUts.get(13-1)),
            new District("Kullu", 20, stateOrUts.get(13-1)),
            new District("Lahaul And Spiti", 21, stateOrUts.get(13-1)),
            new District("Mandi", 22, stateOrUts.get(13-1)),
            new District("Shimla", 23, stateOrUts.get(13-1)),
            new District("Sirmaur", 24, stateOrUts.get(13-1)),
            new District("Solan", 25, stateOrUts.get(13-1)),
            new District("Una", 26, stateOrUts.get(13-1)),

            new District("Anantnag", 1, stateOrUts.get(14-1)),
            new District("Bandipora", 623, stateOrUts.get(14-1)),
            new District("Baramulla", 3, stateOrUts.get(14-1)),
            new District("Budgam", 2, stateOrUts.get(14-1)),
            new District("Doda", 4, stateOrUts.get(14-1)),
            new District("Ganderbal", 626, stateOrUts.get(14-1)),
            new District("Jammu", 5, stateOrUts.get(14-1)),
            new District("Kathua", 7, stateOrUts.get(14-1)),
            new District("Kishtwar", 620, stateOrUts.get(14-1)),
            new District("Kulgam", 622, stateOrUts.get(14-1)),
            new District("Kupwara", 8, stateOrUts.get(14-1)),
            new District("Poonch", 10, stateOrUts.get(14-1)),
            new District("Pulwama", 11, stateOrUts.get(14-1)),
            new District("Rajouri", 12, stateOrUts.get(14-1)),
            new District("Ramban", 621, stateOrUts.get(14-1)),
            new District("Reasi", 627, stateOrUts.get(14-1)),
            new District("Samba", 624, stateOrUts.get(14-1)),
            new District("Shopian", 625, stateOrUts.get(14-1)),
            new District("Srinagar", 13, stateOrUts.get(14-1)),
            new District("Udhampur", 14, stateOrUts.get(14-1)),

            new District("Bokaro", 322, stateOrUts.get(15-1)),
            new District("Chatra", 323, stateOrUts.get(15-1)),
            new District("Deoghar", 324, stateOrUts.get(15-1)),
            new District("Dhanbad", 325, stateOrUts.get(15-1)),
            new District("Dumka", 326, stateOrUts.get(15-1)),
            new District("East Singhbum", 327, stateOrUts.get(15-1)),
            new District("Garhwa", 328, stateOrUts.get(15-1)),
            new District("Giridih", 329, stateOrUts.get(15-1)),
            new District("Godda", 330, stateOrUts.get(15-1)),
            new District("Gumla", 331, stateOrUts.get(15-1)),
            new District("Hazaribagh", 332, stateOrUts.get(15-1)),
            new District("Jamtara", 333, stateOrUts.get(15-1)),
            new District("Khunti", 606, stateOrUts.get(15-1)),
            new District("Koderma", 334, stateOrUts.get(15-1)),
            new District("Latehar", 335, stateOrUts.get(15-1)),
            new District("Lohardaga", 336, stateOrUts.get(15-1)),
            new District("Pakur", 337, stateOrUts.get(15-1)),
            new District("Palamu", 338, stateOrUts.get(15-1)),
            new District("Ramgarh", 607, stateOrUts.get(15-1)),
            new District("Ranchi", 339, stateOrUts.get(15-1)),
            new District("Sahebganj", 340, stateOrUts.get(15-1)),
            new District("Saraikela Kharsawan", 341, stateOrUts.get(15-1)),
            new District("Simdega", 342, stateOrUts.get(15-1)),
            new District("West Singhbhum", 343, stateOrUts.get(15-1)),

            new District("Bagalkote", 524, stateOrUts.get(16-1)),
            new District("Ballari", 528, stateOrUts.get(16-1)),
            new District("Belagavi", 527, stateOrUts.get(16-1)),
            new District("Bengaluru Rural", 526, stateOrUts.get(16-1)),
            new District("Bengaluru South", 631, stateOrUts.get(16-1)),
            new District("Bengaluru Urban", 525, stateOrUts.get(16-1)),
            new District("Bidar", 529, stateOrUts.get(16-1)),
            new District("Chamarajanagar", 531, stateOrUts.get(16-1)),
            new District("Chikkaballapura", 630, stateOrUts.get(16-1)),
            new District("Chikkamagaluru", 532, stateOrUts.get(16-1)),
            new District("Chitradurga", 533, stateOrUts.get(16-1)),
            new District("Dakshina Kannada", 534, stateOrUts.get(16-1)),
            new District("Davanagere", 535, stateOrUts.get(16-1)),
            new District("Dharwad", 536, stateOrUts.get(16-1)),
            new District("Gadag", 537, stateOrUts.get(16-1)),
            new District("Hassan", 539, stateOrUts.get(16-1)),
            new District("Haveri", 540, stateOrUts.get(16-1)),
            new District("Kalaburagi", 538, stateOrUts.get(16-1)),
            new District("Kodagu", 541, stateOrUts.get(16-1)),
            new District("Kolar", 542, stateOrUts.get(16-1)),
            new District("Koppal", 543, stateOrUts.get(16-1)),
            new District("Mandya", 544, stateOrUts.get(16-1)),
            new District("Mysuru", 545, stateOrUts.get(16-1)),
            new District("Raichur", 546, stateOrUts.get(16-1)),
            new District("Shivamogga", 547, stateOrUts.get(16-1)),
            new District("Tumakuru", 548, stateOrUts.get(16-1)),
            new District("Udupi", 549, stateOrUts.get(16-1)),
            new District("Uttara Kannada", 550, stateOrUts.get(16-1)),
            new District("Vijayanagara", 738, stateOrUts.get(16-1)),
            new District("Vijayapura", 530, stateOrUts.get(16-1)),
            new District("Yadgir", 635, stateOrUts.get(16-1)),

            new District("Alappuzha", 554, stateOrUts.get(17-1)),
            new District("Ernakulam", 555, stateOrUts.get(17-1)),
            new District("Idukki", 556, stateOrUts.get(17-1)),
            new District("Kannur", 557, stateOrUts.get(17-1)),
            new District("Kasaragod", 558, stateOrUts.get(17-1)),
            new District("Kollam", 559, stateOrUts.get(17-1)),
            new District("Kottayam", 560, stateOrUts.get(17-1)),
            new District("Kozhikode", 561, stateOrUts.get(17-1)),
            new District("Malappuram", 562, stateOrUts.get(17-1)),
            new District("Palakkad", 563, stateOrUts.get(17-1)),
            new District("Pathanamthitta", 564, stateOrUts.get(17-1)),
            new District("Thiruvananthapuram", 565, stateOrUts.get(17-1)),
            new District("Thrissur", 566, stateOrUts.get(17-1)),
            new District("Wayanad", 567, stateOrUts.get(17-1)),

            new District("Kargil", 6, stateOrUts.get(18-1)),
            new District("Leh Ladakh", 9, stateOrUts.get(18-1)),

            new District("Lakshadweep", 553, stateOrUts.get(19-1)),

            new District("Agar-Malwa", 667, stateOrUts.get(20-1)),
            new District("Alirajpur", 639, stateOrUts.get(20-1)),
            new District("Anuppur", 390, stateOrUts.get(20-1)),
            new District("Ashoknagar", 391, stateOrUts.get(20-1)),
            new District("Balaghat", 392, stateOrUts.get(20-1)),
            new District("Barwani", 393, stateOrUts.get(20-1)),
            new District("Betul", 394, stateOrUts.get(20-1)),
            new District("Bhind", 395, stateOrUts.get(20-1)),
            new District("Bhopal", 396, stateOrUts.get(20-1)),
            new District("Burhanpur", 397, stateOrUts.get(20-1)),
            new District("Chhatarpur", 398, stateOrUts.get(20-1)),
            new District("Chhindwara", 399, stateOrUts.get(20-1)),
            new District("Damoh", 400, stateOrUts.get(20-1)),
            new District("Datia", 401, stateOrUts.get(20-1)),
            new District("Dewas", 402, stateOrUts.get(20-1)),
            new District("Dhar", 403, stateOrUts.get(20-1)),
            new District("Dindori", 404, stateOrUts.get(20-1)),
            new District("Guna", 406, stateOrUts.get(20-1)),
            new District("Gwalior", 407, stateOrUts.get(20-1)),
            new District("Harda", 408, stateOrUts.get(20-1)),
            new District("Indore", 410, stateOrUts.get(20-1)),
            new District("Jabalpur", 411, stateOrUts.get(20-1)),
            new District("Jhabua", 412, stateOrUts.get(20-1)),
            new District("Katni", 413, stateOrUts.get(20-1)),
            new District("Khandwa (East NimstateOrUts.get(ar-1))", 405, stateOrUts.get(20-1)),
            new District("Khargone (West NimstateOrUts.get(ar-1))", 414, stateOrUts.get(20-1)),
            new District("Maihar", 784, stateOrUts.get(20-1)),
            new District("Mandla", 415, stateOrUts.get(20-1)),
            new District("Mandsaur", 416, stateOrUts.get(20-1)),
            new District("MAUGANJ", 766, stateOrUts.get(20-1)),
            new District("Morena", 417, stateOrUts.get(20-1)),
            new District("Narmadapuram", 409, stateOrUts.get(20-1)),
            new District("Narsimhapur", 418, stateOrUts.get(20-1)),
            new District("Neemuch", 419, stateOrUts.get(20-1)),
            new District("Niwari", 722, stateOrUts.get(20-1)),
            new District("Pandhurna", 785, stateOrUts.get(20-1)),
            new District("Panna", 420, stateOrUts.get(20-1)),
            new District("Raisen", 421, stateOrUts.get(20-1)),
            new District("Rajgarh", 422, stateOrUts.get(20-1)),
            new District("Ratlam", 423, stateOrUts.get(20-1)),
            new District("Rewa", 424, stateOrUts.get(20-1)),
            new District("Sagar", 425, stateOrUts.get(20-1)),
            new District("Satna", 426, stateOrUts.get(20-1)),
            new District("Sehore", 427, stateOrUts.get(20-1)),
            new District("Seoni", 428, stateOrUts.get(20-1)),
            new District("Shahdol", 429, stateOrUts.get(20-1)),
            new District("Shajapur", 430, stateOrUts.get(20-1)),
            new District("Sheopur", 431, stateOrUts.get(20-1)),
            new District("Shivpuri", 432, stateOrUts.get(20-1)),
            new District("Sidhi", 433, stateOrUts.get(20-1)),
            new District("Singrauli", 638, stateOrUts.get(20-1)),
            new District("Tikamgarh", 434, stateOrUts.get(20-1)),
            new District("Ujjain", 435, stateOrUts.get(20-1)),
            new District("Umaria", 436, stateOrUts.get(20-1)),
            new District("Vidisha", 437, stateOrUts.get(20-1)),

            new District("Ahilyanagar", 466, stateOrUts.get(21-1)),
            new District("Akola", 467, stateOrUts.get(21-1)),
            new District("Amravati", 468, stateOrUts.get(21-1)),
            new District("Beed", 470, stateOrUts.get(21-1)),
            new District("Bhandara", 471, stateOrUts.get(21-1)),
            new District("Buldhana", 472, stateOrUts.get(21-1)),
            new District("Chandrapur", 473, stateOrUts.get(21-1)),
            new District("Chhatrapati Sambhajinagar", 469, stateOrUts.get(21-1)),
            new District("Dharashiv", 488, stateOrUts.get(21-1)),
            new District("Dhule", 474, stateOrUts.get(21-1)),
            new District("Gadchiroli", 475, stateOrUts.get(21-1)),
            new District("Gondia", 476, stateOrUts.get(21-1)),
            new District("Hingoli", 477, stateOrUts.get(21-1)),
            new District("Jalgaon", 478, stateOrUts.get(21-1)),
            new District("Jalna", 479, stateOrUts.get(21-1)),
            new District("Kolhapur", 480, stateOrUts.get(21-1)),
            new District("Latur", 481, stateOrUts.get(21-1)),
            new District("Mumbai", 482, stateOrUts.get(21-1)),
            new District("Mumbai Suburban", 483, stateOrUts.get(21-1)),
            new District("Nagpur", 484, stateOrUts.get(21-1)),
            new District("Nanded", 485, stateOrUts.get(21-1)),
            new District("Nandurbar", 486, stateOrUts.get(21-1)),
            new District("Nashik", 487, stateOrUts.get(21-1)),
            new District("Palghar", 665, stateOrUts.get(21-1)),
            new District("Parbhani", 489, stateOrUts.get(21-1)),
            new District("Pune", 490, stateOrUts.get(21-1)),
            new District("Raigad", 491, stateOrUts.get(21-1)),
            new District("Ratnagiri", 492, stateOrUts.get(21-1)),
            new District("Sangli", 493, stateOrUts.get(21-1)),
            new District("Satara", 494, stateOrUts.get(21-1)),
            new District("Sindhudurg", 495, stateOrUts.get(21-1)),
            new District("Solapur", 496, stateOrUts.get(21-1)),
            new District("Thane", 497, stateOrUts.get(21-1)),
            new District("Wardha", 498, stateOrUts.get(21-1)),
            new District("Washim", 499, stateOrUts.get(21-1)),
            new District("Yavatmal", 500, stateOrUts.get(21-1)),

            new District("Bishnupur", 252, stateOrUts.get(22-1)),
            new District("Chandel", 253, stateOrUts.get(22-1)),
            new District("Churachandpur", 254, stateOrUts.get(22-1)),
            new District("Imphal East", 255, stateOrUts.get(22-1)),
            new District("Imphal West", 256, stateOrUts.get(22-1)),
            new District("Jiribam", 713, stateOrUts.get(22-1)),
            new District("Kakching", 711, stateOrUts.get(22-1)),
            new District("Kamjong", 717, stateOrUts.get(22-1)),
            new District("Kangpokpi", 712, stateOrUts.get(22-1)),
            new District("Noney", 714, stateOrUts.get(22-1)),
            new District("Pherzawl", 715, stateOrUts.get(22-1)),
            new District("Senapati", 257, stateOrUts.get(22-1)),
            new District("Tamenglong", 258, stateOrUts.get(22-1)),
            new District("Tengnoupal", 716, stateOrUts.get(22-1)),
            new District("Thoubal", 259, stateOrUts.get(22-1)),
            new District("Ukhrul", 260, stateOrUts.get(22-1)),

            new District("Eastern West Khasi Hills", 740, stateOrUts.get(23-1)),
            new District("East Garo Hills", 273, stateOrUts.get(23-1)),
            new District("East Jaintia Hills", 657, stateOrUts.get(23-1)),
            new District("East Khasi Hills", 274, stateOrUts.get(23-1)),
            new District("North Garo Hills", 656, stateOrUts.get(23-1)),
            new District("Ri Bhoi", 276, stateOrUts.get(23-1)),
            new District("South Garo Hills", 277, stateOrUts.get(23-1)),
            new District("South West Garo Hills", 663, stateOrUts.get(23-1)),
            new District("South West Khasi Hills", 658, stateOrUts.get(23-1)),
            new District("West Garo Hills", 278, stateOrUts.get(23-1)),
            new District("West Jaintia Hills", 275, stateOrUts.get(23-1)),
            new District("West Khasi Hills", 279, stateOrUts.get(23-1)),

            new District("Aizawl", 261, stateOrUts.get(24-1)),

            new District("Champhai", 262, stateOrUts.get(24-1)),
            new District("Hnahthial", 726, stateOrUts.get(24-1)),
            new District("Khawzawl", 728, stateOrUts.get(24-1)),
            new District("Kolasib", 263, stateOrUts.get(24-1)),
            new District("Lawngtlai", 264, stateOrUts.get(24-1)),
            new District("Lunglei", 265, stateOrUts.get(24-1)),
            new District("Mamit", 266, stateOrUts.get(24-1)),
            new District("Saitual", 727, stateOrUts.get(24-1)),
            new District("Serchhip", 268, stateOrUts.get(24-1)),
            new District("Siaha", 267, stateOrUts.get(24-1)),

            new District("Chumoukedima", 758, stateOrUts.get(25-1)),
            new District("Dimapur", 244, stateOrUts.get(25-1)),
            new District("Kiphire", 614, stateOrUts.get(25-1)),
            new District("Kohima", 245, stateOrUts.get(25-1)),
            new District("Longleng", 615, stateOrUts.get(25-1)),
            new District("Meluri", 788, stateOrUts.get(25-1)),
            new District("Mokokchung", 246, stateOrUts.get(25-1)),
            new District("Mon", 247, stateOrUts.get(25-1)),
            new District("Niuland", 764, stateOrUts.get(25-1)),
            new District("Noklak", 736, stateOrUts.get(25-1)),
            new District("Peren", 613, stateOrUts.get(25-1)),
            new District("Phek", 248, stateOrUts.get(25-1)),
            new District("Shamator", 765, stateOrUts.get(25-1)),
            new District("Tseminyu", 757, stateOrUts.get(25-1)),
            new District("Tuensang", 249, stateOrUts.get(25-1)),
            new District("Wokha", 250, stateOrUts.get(25-1)),
            new District("Zunheboto", 251, stateOrUts.get(25-1)),

            new District("Angul", 344, stateOrUts.get(26-1)),
            new District("Balangir", 345, stateOrUts.get(26-1)),
            new District("Balasore", 346, stateOrUts.get(26-1)),
            new District("Bargarh", 347, stateOrUts.get(26-1)),
            new District("Bhadrak", 348, stateOrUts.get(26-1)),
            new District("Boudh", 349, stateOrUts.get(26-1)),
            new District("Cuttack", 350, stateOrUts.get(26-1)),
            new District("Deogarh", 351, stateOrUts.get(26-1)),
            new District("Dhenkanal", 352, stateOrUts.get(26-1)),
            new District("Gajapati", 353, stateOrUts.get(26-1)),
            new District("Ganjam", 354, stateOrUts.get(26-1)),
            new District("Jagatsinghapur", 355, stateOrUts.get(26-1)),
            new District("Jajpur", 356, stateOrUts.get(26-1)),
            new District("Jharsuguda", 357, stateOrUts.get(26-1)),
            new District("Kalahandi", 358, stateOrUts.get(26-1)),
            new District("Kandhamal", 359, stateOrUts.get(26-1)),
            new District("Kendrapara", 360, stateOrUts.get(26-1)),
            new District("Keonjhar", 361, stateOrUts.get(26-1)),
            new District("Khordha", 362, stateOrUts.get(26-1)),
            new District("Koraput", 363, stateOrUts.get(26-1)),
            new District("Malkangiri", 364, stateOrUts.get(26-1)),
            new District("Mayurbhanj", 365, stateOrUts.get(26-1)),
            new District("Nabarangpur", 366, stateOrUts.get(26-1)),
            new District("Nayagarh", 367, stateOrUts.get(26-1)),
            new District("Nuapada", 368, stateOrUts.get(26-1)),
            new District("Puri", 369, stateOrUts.get(26-1)),
            new District("Rayagada", 370, stateOrUts.get(26-1)),
            new District("Sambalpur", 371, stateOrUts.get(26-1)),
            new District("Sonepur", 372, stateOrUts.get(26-1)),
            new District("Sundargarh", 373, stateOrUts.get(26-1)),

            new District("Karaikal", 598, stateOrUts.get(27-1)),
            new District("Puducherry", 600, stateOrUts.get(27-1)),

            new District("Amritsar", 27, stateOrUts.get(28-1)),
            new District("Barnala", 605, stateOrUts.get(28-1)),
            new District("Bathinda", 28, stateOrUts.get(28-1)),
            new District("Faridkot", 29, stateOrUts.get(28-1)),
            new District("Fatehgarh Sahib", 30, stateOrUts.get(28-1)),
            new District("Fazilka", 651, stateOrUts.get(28-1)),
            new District("Ferozepur", 31, stateOrUts.get(28-1)),
            new District("Gurdaspur", 32, stateOrUts.get(28-1)),
            new District("Hoshiarpur", 33, stateOrUts.get(28-1)),
            new District("Jalandhar", 34, stateOrUts.get(28-1)),
            new District("Kapurthala", 35, stateOrUts.get(28-1)),
            new District("Ludhiana", 36, stateOrUts.get(28-1)),
            new District("Malerkotla", 737, stateOrUts.get(28-1)),
            new District("Mansa", 37, stateOrUts.get(28-1)),
            new District("Moga", 38, stateOrUts.get(28-1)),
            new District("Pathankot", 662, stateOrUts.get(28-1)),
            new District("Patiala", 41, stateOrUts.get(28-1)),
            new District("Rupnagar", 42, stateOrUts.get(28-1)),
            new District("Sangrur", 43, stateOrUts.get(28-1)),
            new District("S.A.S Nagar", 608, stateOrUts.get(28-1)),
            new District("Shahid Bhagat Singh Nagar", 40, stateOrUts.get(28-1)),
            new District("Sri Muktsar Sahib", 39, stateOrUts.get(28-1)),
            new District("Tarn Taran", 609, stateOrUts.get(28-1)),

            new District("Ajmer", 86, stateOrUts.get(29-1)),
            new District("Alwar", 87, stateOrUts.get(29-1)),
            new District("Balotra", 775, stateOrUts.get(29-1)),
            new District("Banswara", 88, stateOrUts.get(29-1)),
            new District("Baran", 89, stateOrUts.get(29-1)),
            new District("Barmer", 90, stateOrUts.get(29-1)),
            new District("Beawar", 774, stateOrUts.get(29-1)),
            new District("Bharatpur", 91, stateOrUts.get(29-1)),
            new District("Bhilwara", 92, stateOrUts.get(29-1)),
            new District("Bikaner", 93, stateOrUts.get(29-1)),
            new District("Bundi", 94, stateOrUts.get(29-1)),
            new District("Chittorgarh", 95, stateOrUts.get(29-1)),
            new District("Churu", 96, stateOrUts.get(29-1)),
            new District("Dausa", 97, stateOrUts.get(29-1)),
            new District("Deeg", 767, stateOrUts.get(29-1)),
            new District("Dholpur", 98, stateOrUts.get(29-1)),
            new District("Didwana-Kuchaman", 768, stateOrUts.get(29-1)),
            new District("Dungarpur", 99, stateOrUts.get(29-1)),
            new District("Ganganagar", 100, stateOrUts.get(29-1)),
            new District("Hanumangarh", 101, stateOrUts.get(29-1)),
            new District("Jaipur", 102, stateOrUts.get(29-1)),
            new District("Jaisalmer", 103, stateOrUts.get(29-1)),
            new District("Jalore", 104, stateOrUts.get(29-1)),
            new District("Jhalawar", 105, stateOrUts.get(29-1)),
            new District("Jhunjhunu", 106, stateOrUts.get(29-1)),
            new District("Jodhpur", 107, stateOrUts.get(29-1)),
            new District("Karauli", 108, stateOrUts.get(29-1)),
            new District("Khairthal-Tijara", 770, stateOrUts.get(29-1)),
            new District("Kota", 109, stateOrUts.get(29-1)),
            new District("Kotputli-Behror", 782, stateOrUts.get(29-1)),
            new District("Nagaur", 110, stateOrUts.get(29-1)),
            new District("Pali", 111, stateOrUts.get(29-1)),
            new District("Phalodi", 772, stateOrUts.get(29-1)),
            new District("Pratapgarh", 629, stateOrUts.get(29-1)),
            new District("Rajsamand", 112, stateOrUts.get(29-1)),
            new District("Salumbar", 777, stateOrUts.get(29-1)),
            new District("Sawai Madhopur", 113, stateOrUts.get(29-1)),
            new District("Sikar", 114, stateOrUts.get(29-1)),
            new District("Sirohi", 115, stateOrUts.get(29-1)),
            new District("Tonk", 116, stateOrUts.get(29-1)),
            new District("Udaipur", 117, stateOrUts.get(29-1)),

            new District("Gangtok", 225, stateOrUts.get(30-1)),
            new District("Gyalshing", 228, stateOrUts.get(30-1)),
            new District("Mangan", 226, stateOrUts.get(30-1)),
            new District("Namchi", 227, stateOrUts.get(30-1)),
            new District("Pakyong", 741, stateOrUts.get(30-1)),
            new District("Soreng", 742, stateOrUts.get(30-1)),

            new District("Ariyalur", 610, stateOrUts.get(31-1)),
            new District("Chengalpattu", 730, stateOrUts.get(31-1)),
            new District("Chennai", 568, stateOrUts.get(31-1)),
            new District("Coimbatore", 569, stateOrUts.get(31-1)),
            new District("Cuddalore", 570, stateOrUts.get(31-1)),
            new District("Dharmapuri", 571, stateOrUts.get(31-1)),
            new District("Dindigul", 572, stateOrUts.get(31-1)),
            new District("Erode", 573, stateOrUts.get(31-1)),
            new District("Kallakurichi", 729, stateOrUts.get(31-1)),
            new District("Kancheepuram", 574, stateOrUts.get(31-1)),
            new District("Kanniyakumari", 575, stateOrUts.get(31-1)),
            new District("Karur", 576, stateOrUts.get(31-1)),
            new District("Krishnagiri", 577, stateOrUts.get(31-1)),
            new District("Madurai", 578, stateOrUts.get(31-1)),
            new District("Mayiladuthurai", 735, stateOrUts.get(31-1)),
            new District("Nagapattinam", 579, stateOrUts.get(31-1)),
            new District("Namakkal", 580, stateOrUts.get(31-1)),
            new District("Perambalur", 581, stateOrUts.get(31-1)),
            new District("Pudukkottai", 582, stateOrUts.get(31-1)),
            new District("Ramanathapuram", 583, stateOrUts.get(31-1)),
            new District("Ranipet", 731, stateOrUts.get(31-1)),
            new District("Salem", 584, stateOrUts.get(31-1)),
            new District("Sivaganga", 585, stateOrUts.get(31-1)),
            new District("Tenkasi", 733, stateOrUts.get(31-1)),
            new District("Thanjavur", 586, stateOrUts.get(31-1)),
            new District("Theni", 588, stateOrUts.get(31-1)),
            new District("The Nilgiris", 587, stateOrUts.get(31-1)),
            new District("Thiruvallur", 589, stateOrUts.get(31-1)),
            new District("Thiruvarur", 590, stateOrUts.get(31-1)),
            new District("Thoothukkudi", 594, stateOrUts.get(31-1)),
            new District("Tiruchirappalli", 591, stateOrUts.get(31-1)),
            new District("Tirunelveli", 592, stateOrUts.get(31-1)),
            new District("Tirupathur", 732, stateOrUts.get(31-1)),
            new District("Tiruppur", 634, stateOrUts.get(31-1)),
            new District("Tiruvannamalai", 593, stateOrUts.get(31-1)),
            new District("Vellore", 595, stateOrUts.get(31-1)),
            new District("Viluppuram", 596, stateOrUts.get(31-1)),
            new District("Virudhunagar", 597, stateOrUts.get(31-1)),

            new District("Adilabad", 501, stateOrUts.get(32-1)),
            new District("Bhadradri Kothagudem", 690, stateOrUts.get(32-1)),
            new District("Hanumakonda", 686, stateOrUts.get(32-1)),
            new District("Hyderabad", 507, stateOrUts.get(32-1)),
            new District("Jagitial", 681, stateOrUts.get(32-1)),
            new District("Jangoan", 689, stateOrUts.get(32-1)),
            new District("Jayashankar Bhupalapally", 687, stateOrUts.get(32-1)),
            new District("Jogulamba Gadwal", 695, stateOrUts.get(32-1)),
            new District("Kamareddy", 685, stateOrUts.get(32-1)),
            new District("Karimnagar", 508, stateOrUts.get(32-1)),
            new District("Khammam", 509, stateOrUts.get(32-1)),
            new District("Kumuram Bheem Asifabad", 699, stateOrUts.get(32-1)),
            new District("Mahabubabad", 688, stateOrUts.get(32-1)),
            new District("Mahabubnagar", 512, stateOrUts.get(32-1)),
            new District("Mancherial", 684, stateOrUts.get(32-1)),
            new District("Medak", 513, stateOrUts.get(32-1)),
            new District("Medchal Malkajgiri", 700, stateOrUts.get(32-1)),
            new District("Mulugu", 720, stateOrUts.get(32-1)),
            new District("Nagarkurnool", 694, stateOrUts.get(32-1)),
            new District("Nalgonda", 514, stateOrUts.get(32-1)),
            new District("Narayanpet", 721, stateOrUts.get(32-1)),
            new District("Nirmal", 680, stateOrUts.get(32-1)),
            new District("Nizamabad", 516, stateOrUts.get(32-1)),
            new District("Peddapalli", 682, stateOrUts.get(32-1)),
            new District("Rajanna Sircilla", 683, stateOrUts.get(32-1)),
            new District("Ranga Reddy", 518, stateOrUts.get(32-1)),
            new District("Sangareddy", 691, stateOrUts.get(32-1)),
            new District("Siddipet", 692, stateOrUts.get(32-1)),
            new District("Suryapet", 696, stateOrUts.get(32-1)),
            new District("Vikarabad", 698, stateOrUts.get(32-1)),
            new District("Wanaparthy", 693, stateOrUts.get(32-1)),
            new District("Warangal", 522, stateOrUts.get(32-1)),
            new District("Yadadri Bhuvanagiri", 697, stateOrUts.get(32-1)),

            new District("Dhalai", 269, stateOrUts.get(33-1)),
            new District("Gomati", 654, stateOrUts.get(33-1)),
            new District("Khowai", 652, stateOrUts.get(33-1)),
            new District("North Tripura", 270, stateOrUts.get(33-1)),
            new District("Sepahijala", 653, stateOrUts.get(33-1)),
            new District("South Tripura", 271, stateOrUts.get(33-1)),
            new District("Unakoti", 655, stateOrUts.get(33-1)),
            new District("West Tripura", 272, stateOrUts.get(33-1)),

            new District("Almora", 45, stateOrUts.get(34-1)),
            new District("Bageshwar", 46, stateOrUts.get(34-1)),
            new District("Chamoli", 47, stateOrUts.get(34-1)),
            new District("Champawat", 48, stateOrUts.get(34-1)),
            new District("Dehradun", 49, stateOrUts.get(34-1)),
            new District("Haridwar", 50, stateOrUts.get(34-1)),
            new District("Nainital", 51, stateOrUts.get(34-1)),
            new District("Pauri Garhwal", 52, stateOrUts.get(34-1)),
            new District("Pithoragarh", 53, stateOrUts.get(34-1)),
            new District("Rudraprayag", 54, stateOrUts.get(34-1)),
            new District("Tehri Garhwal", 55, stateOrUts.get(34-1)),
            new District("Udham Singh Nagar", 56, stateOrUts.get(34-1)),
            new District("Uttarkashi", 57, stateOrUts.get(34-1)),

            new District("Agra", 118, stateOrUts.get(35-1)),
            new District("Aligarh", 119, stateOrUts.get(35-1)),
            new District("Ambedkar Nagar", 121, stateOrUts.get(35-1)),
            new District("Amethi", 640, stateOrUts.get(35-1)),
            new District("Amroha", 154, stateOrUts.get(35-1)),
            new District("Auraiya", 122, stateOrUts.get(35-1)),
            new District("Ayodhya", 140, stateOrUts.get(35-1)),
            new District("Azamgarh", 123, stateOrUts.get(35-1)),
            new District("Baghpat", 124, stateOrUts.get(35-1)),
            new District("Bahraich", 125, stateOrUts.get(35-1)),
            new District("Ballia", 126, stateOrUts.get(35-1)),
            new District("Balrampur", 127, stateOrUts.get(35-1)),
            new District("Banda", 128, stateOrUts.get(35-1)),
            new District("Bara Banki", 129, stateOrUts.get(35-1)),
            new District("Bareilly", 130, stateOrUts.get(35-1)),
            new District("Basti", 131, stateOrUts.get(35-1)),
            new District("Bhadohi", 179, stateOrUts.get(35-1)),
            new District("Bijnor", 132, stateOrUts.get(35-1)),
            new District("Budaun", 133, stateOrUts.get(35-1)),
            new District("Bulandshahr", 134, stateOrUts.get(35-1)),
            new District("Chandauli", 135, stateOrUts.get(35-1)),
            new District("Chitrakoot", 136, stateOrUts.get(35-1)),
            new District("Deoria", 137, stateOrUts.get(35-1)),
            new District("Etah", 138, stateOrUts.get(35-1)),
            new District("Etawah", 139, stateOrUts.get(35-1)),
            new District("Farrukhabad", 141, stateOrUts.get(35-1)),
            new District("Fatehpur", 142, stateOrUts.get(35-1)),
            new District("Firozabad", 143, stateOrUts.get(35-1)),
            new District("Gautam Buddha Nagar", 144, stateOrUts.get(35-1)),
            new District("Ghaziabad", 145, stateOrUts.get(35-1)),
            new District("Ghazipur", 146, stateOrUts.get(35-1)),
            new District("Gonda", 147, stateOrUts.get(35-1)),
            new District("Gorakhpur", 148, stateOrUts.get(35-1)),
            new District("Hamirpur", 149, stateOrUts.get(35-1)),
            new District("Hapur", 661, stateOrUts.get(35-1)),
            new District("Hardoi", 150, stateOrUts.get(35-1)),
            new District("Hathras", 163, stateOrUts.get(35-1)),
            new District("Jalaun", 151, stateOrUts.get(35-1)),
            new District("Jaunpur", 152, stateOrUts.get(35-1)),
            new District("Jhansi", 153, stateOrUts.get(35-1)),
            new District("Kannauj", 155, stateOrUts.get(35-1)),
            new District("Kanpur Dehat", 156, stateOrUts.get(35-1)),
            new District("Kanpur Nagar", 157, stateOrUts.get(35-1)),
            new District("Kasganj", 633, stateOrUts.get(35-1)),
            new District("Kaushambi", 158, stateOrUts.get(35-1)),
            new District("Kheri", 159, stateOrUts.get(35-1)),
            new District("Kushinagar", 160, stateOrUts.get(35-1)),
            new District("Lalitpur", 161, stateOrUts.get(35-1)),
            new District("Lucknow", 162, stateOrUts.get(35-1)),
            new District("Mahoba", 165, stateOrUts.get(35-1)),
            new District("Mahrajganj", 164, stateOrUts.get(35-1)),
            new District("Mainpuri", 166, stateOrUts.get(35-1)),
            new District("Mathura", 167, stateOrUts.get(35-1)),
            new District("Mau", 168, stateOrUts.get(35-1)),
            new District("Meerut", 169, stateOrUts.get(35-1)),
            new District("Mirzapur", 170, stateOrUts.get(35-1)),
            new District("Moradabad", 171, stateOrUts.get(35-1)),
            new District("Muzaffarnagar", 172, stateOrUts.get(35-1)),
            new District("Pilibhit", 173, stateOrUts.get(35-1)),
            new District("Pratapgarh", 174, stateOrUts.get(35-1)),
            new District("Prayagraj", 120, stateOrUts.get(35-1)),
            new District("Rae Bareli", 175, stateOrUts.get(35-1)),
            new District("Rampur", 176, stateOrUts.get(35-1)),
            new District("Saharanpur", 177, stateOrUts.get(35-1)),
            new District("Sambhal", 659, stateOrUts.get(35-1)),
            new District("Sant Kabir Nagar", 178, stateOrUts.get(35-1)),
            new District("Shahjahanpur", 180, stateOrUts.get(35-1)),
            new District("Shamli", 660, stateOrUts.get(35-1)),
            new District("Shrawasti", 181, stateOrUts.get(35-1)),
            new District("Siddharthnagar", 182, stateOrUts.get(35-1)),
            new District("Sitapur", 183, stateOrUts.get(35-1)),
            new District("Sonbhadra", 184, stateOrUts.get(35-1)),
            new District("Sultanpur", 185, stateOrUts.get(35-1)),
            new District("Unnao", 186, stateOrUts.get(35-1)),
            new District("Varanasi", 187, stateOrUts.get(35-1)),

            new District("Alipurduar", 664, stateOrUts.get(36-1)),
            new District("Bankura", 305, stateOrUts.get(36-1)),
            new District("Birbhum", 307, stateOrUts.get(36-1)),
            new District("Cooch Behar", 308, stateOrUts.get(36-1)),
            new District("Dakshin Dinajpur", 310, stateOrUts.get(36-1)),
            new District("Darjeeling", 309, stateOrUts.get(36-1)),
            new District("Hooghly", 312, stateOrUts.get(36-1)),
            new District("Howrah", 313, stateOrUts.get(36-1)),
            new District("Jalpaiguri", 314, stateOrUts.get(36-1)),
            new District("Jhargram", 703, stateOrUts.get(36-1)),
            new District("Kalimpong", 702, stateOrUts.get(36-1)),
            new District("Kolkata", 315, stateOrUts.get(36-1)),
            new District("Malda", 316, stateOrUts.get(36-1)),
            new District("Murshidabad", 319, stateOrUts.get(36-1)),
            new District("Nadia", 320, stateOrUts.get(36-1)),
            new District("North 24 Parganas", 303, stateOrUts.get(36-1)),
            new District("Paschim Bardhaman", 704, stateOrUts.get(36-1)),
            new District("Paschim Medinipur", 318, stateOrUts.get(36-1)),
            new District("Purba Bardhaman", 306, stateOrUts.get(36-1)),
            new District("Purba Medinipur", 317, stateOrUts.get(36-1)),
            new District("Purulia", 321, stateOrUts.get(36-1)),
            new District("South 24 Parganas", 304, stateOrUts.get(36-1)),
            new District("Uttar Dinajpur", 311, stateOrUts.get(36-1)));

    List<Role> roles = List.of(new Role(RoleEnum.ADMIN, "Admin Can do anything"),
                                new Role(RoleEnum.RESIDENT, "Residents can see alterts"),
                                new Role(RoleEnum.RESPONDENT, "Respondents can rescue and submit reports"));

    public void saveLocation() throws Exception {

        try{
            stateOrUtRepo.saveAll(stateOrUts);
            districtRepo.saveAll(districts);
            roleRepo.saveAll(roles);
        }
        catch(Exception e){
            System.out.println("Data already exista");
        }
        


    }

    @Override
    public void afterPropertiesSet() throws Exception {
        saveLocation();
        
    }

  

}
